stolostron/application-ui

lib/shared/constants.js, src-web/components/Topology/viewer/constants.js, src-web/components/common/AutoRefreshSelect.js, tests/jest/components/common/__snapshots__/AutoRefreshSelect_appsTable.test.js.snap, tests/jest/components/common/__snapshots__/AutoRefreshSelect_singleApp.test.js.snap
https://github.com/open-cluster-management/backlog/issues/10182
=> set default refresh value to 15s

sonar-project.properties
- Adding line return to fix sonar test
=> add \n in sonar-project.properties

Dockerfile.prow
Remove unnecessary params from dockerfile.prow
=> remove unnecessary params in dockerfile.prow

tests/cypress/README.md
This change is to kick off prow publish
=> no-op change to kickoff prow

.dockerignore, Dockerfile.prow
https://github.com/open-cluster-management/backlog/issues/10360
- fix app-ui image builder
=> app-ui image buider

.nvmrc, Dockerfile, build/run-e2e-tests-clusterpool.sh, run-cypress.sh
open-cluster-management/backlog#9535
=> upgrade nodejs version

lib/client/resource-helper.js, src-web/components/common/OverviewCards/index.js, src-web/components/common/ResourceOverview/utils.js, tests/jest/components/common/ResourceOverview/utils.test.js, tests/jest/lib/client/resource-helper.test.js
https://github.com/open-cluster-management/backlog/issues/9288
Clusters link:
-------------------
Search resource link:
=> Update overview cards for Argo applications

package-lock.json, package.json, src-web/components/common/ResourceTable.js, tests/cypress/tests/02-validate/05-validate-table-state.spec.js, tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap, tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap, tests/jest/components/common/__snapshots__/ResourceList.test.js.snap
=> Adopt new ui-components table design

controllers/ui/index.js, package-lock.json, package.json
As per https://coreos.slack.com/archives/CUPTCTQR2/p1616072673002500
=> Use security-middleware from npmjs.com

nls/platform.properties, src-web/components/common/ChannelLabels.js, src-web/components/common/OverviewCards/index.js, src-web/components/common/OverviewCards/style.scss, src-web/components/common/ResourceOverview/utils.js, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap, tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap, tests/jest/components/common/ResourceOverview/utils.test.js, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/9288
=> Update app overview cards based on Argo CD integration design

package-lock.json, package.json, tests/cypress/tests/02-validate/05-validate-table-state.spec.js, tests/cypress/views/application.js
https://github.com/open-cluster-management/backlog/issues/9610
Updated `lodash` to version `4.17.21`
=> Update lodash to fix a security issue in 2.2

src-web/components/common/OverviewCards/index.js, src-web/components/common/TimeWindowLabels.js, tests/jest/components/common/OverviewCards/OverviewCards.test.js, tests/jest/components/common/TimeWindowLabels.test.js
https://github.com/open-cluster-management/backlog/issues/10650
=> route timewindow links to edit tab

src-web/components/Topology/utils/diagram-helpers.js, tests/cypress/tests/02-validate/05-validate-table-state.spec.js, tests/jest/components/Topology/viewer/defaults/details.test.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
open-cluster-management/backlog#10594
=> Top level app sub links 2.2

nls/platform.properties, src-web/components/common/OverviewCards/index.js, src-web/components/common/ResourceOverview/utils.js, tests/jest/components/common/ResourceOverview/utils.test.js, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/9288
=> Use all source properties in building Argo apps search link

src-web/components/Topology/utils/diagram-helpers.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Fix for https://github.com/open-cluster-management/backlog/issues/10585
=> Add view resource link for ansible jobs with missing specs.raw.spec

lib/client/queries.js
open-cluster-management/backlog#10362
=> Do not request selfLink from search queries

tests/cypress/tests/04-delete/01-delete-app.spec.js, tests/cypress/tests/04-delete/02-validate-hub-resource-deletion.spec.js, tests/cypress/tests/04-delete/03-delete-resources.spec.js
https://github.com/open-cluster-management/backlog/issues/10820
=> Skip deleting resources test if running on canary

src-web/components/ApplicationCreationPage/ApplicationCreationPage.js, src-web/components/SecondaryHeader.js
open-cluster-management/backlog#10883
=> Preserve search on tab change

src-web/containers/App.js
Hide editor tab for argoCD applications
https://github.com/open-cluster-management/backlog/issues/10844
=> Hide editor tab

scss/common.scss, scss/table.scss
open-cluster-management/backlog#10894
open-cluster-management/backlog#10895
=> Styling issues

src-web/components/Topology/utils/diagram-helpers-utils.js, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
fix offline status, a cluster is online if 
- status in ok, OK, pendingimport or
- ManagedClusterConditionAvailable = 'True'
=> fix offline clusters

src-web/actions/topology.js, tests/jest/components/Topology/viewer/ClusterDetailsContainer.test.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
after babel version change this no longer works
```
const targetNS = new Set()
...
appData.targetNamespaces = [...targetNS]
```
=> fix issue with Set

src-web/actions/topology.js, src-web/components/Topology/scss/topology-details.scss, src-web/components/Topology/viewer/DetailsView.js, src-web/components/common/OverviewCards/index.js, src-web/components/common/OverviewCards/style.scss, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap, tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
https://github.com/open-cluster-management/backlog/issues/10739
=> fix argo link in details card

src-web/components/Topology/utils/diagram-helpers-utils.js, src-web/components/Topology/utils/diagram-helpers.js, tests/cypress/config/config.func.yaml, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
epic https://github.com/open-cluster-management/backlog/issues/9267
When argo target server uses the cluster api url, try to map that with the actual cluster name
Before
After
=> update argo server - cluster mapping

src-web/components/Topology/utils/diagram-helpers-utils.js
https://github.com/open-cluster-management/backlog/issues/10943
- Added `Missing`, `Degraded`, `Suspended` Argo statuses to the error check
- Mapped the six Argo statuses to the four ACM statuses
=> Add more Argo statuses to error check

tests/cypress/support/commands.js
fix canary build failure
https://github.com/open-cluster-management/backlog/issues/11452
https://github.com/open-cluster-management/backlog/issues/11452#issuecomment-819471649
=> use new page header pf-c-page__header

tests/cypress/config/config.e2e.yaml, tests/cypress/config/config.func.yaml, tests/cypress/views/application.js, tests/cypress/views/common.js
https://github.com/open-cluster-management/backlog/issues/10745
=> Add Cypress tests for UI improvements on subscribed applications

src-web/definitions/hcm-applications.js
open-cluster-management/backlog#9034
=> Remove namespace for Argo groups and fix search link

package-lock.json, package.json, src-web/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/index.js, src-web/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/style.scss, tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap, tests/jest/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/__snapshots__/ApplicationDeploymentHighlightsTerminology.test.js.snap, tests/jest/components/__snapshots__/ApplicationDeploymentHighlights.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_acm.test.js.snap, tests/jest/components/common/ResourceDetails/__snapshots__/ResourceDetails_argo.test.js.snap, tests/jest/components/common/ResourceOverview/__snapshots__/ResourceOverview.test.js.snap
https://github.com/open-cluster-management/backlog/issues/10702
=> update expandable cards

src-web/components/ApplicationCreationPage/components/TimeWindow.js
https://github.com/open-cluster-management/backlog/issues/10812
=> Fix validation and parsing for time window value

src-web/components/common/OverviewCards/index.js
https://github.com/open-cluster-management/backlog/issues/11402
Get the correct cluster info for Launch argo editor
Also patched ui-hub with this change, FYI @KevinFCormier
=> Use topology instead of HCMApplicationList

src-web/components/ApplicationCreationPage/components/TimeWindow.js
Fix for https://github.com/open-cluster-management/backlog/issues/11467
=> Remove space from time window format

scss/secondary-header.scss, src-web/components/SecondaryHeader.js, tests/jest/components/SecondaryHeader.test.js, tests/jest/components/__snapshots__/SecondaryHeader.test.js.snap
https://github.com/open-cluster-management/backlog/issues/11430
=> fix secondary header resizing

src-web/components/Topology/scss/topology-controls.scss, src-web/components/common/OverviewCards/style.scss
https://github.com/open-cluster-management/backlog/issues/10106
=> fix search bar styling for single app page

src-web/components/Topology/viewer/helpers/nodeHelper.js
https://github.com/open-cluster-management/backlog/issues/11231
- Fix cluster count not refreshing when changing users
- This also fixes the cluster count mismatch for ArgoCD apps
=> Fix cluster count not refreshing

CONTRIBUTING.md
open-cluster-management/backlog#11695
=> Add content for commit-sign-off

src-web/components/ApplicationCreationPage/controlData/utils.js, tests/jest/components/CreateApplicationPage/controlData/ControlData.test.js
https://github.com/open-cluster-management/backlog/issues/11486
=> Exclude MCH Helm repo from available repositories

src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js, src-web/components/Topology/utils/diagram-helpers-utils.js, src-web/components/Topology/utils/diagram-helpers.js, src-web/components/Topology/viewer/ClusterDetailsContainer.js, src-web/components/Topology/viewer/defaults/filtering.js, src-web/components/Topology/viewer/defaults/status.js, tests/cypress/config/config.e2e.yaml, tests/cypress/config/config.func.yaml, tests/cypress/config/index.js, tests/jest/components/ApplicationTopologyModule/definitions/hcm-application-diagram.test.js, tests/jest/components/Topology/viewer/defaults/details.test.js, tests/jest/components/Topology/viewer/defaults/filtering.test.js, tests/jest/components/Topology/viewer/defaults/uuu.test.js, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
https://github.com/open-cluster-management/backlog/issues/9142
https://github.com/open-cluster-management/backlog/issues/9405
fixing the app crash
https://github.com/open-cluster-management/backlog/issues/11740
=> show not deployed and offline nodes

nls/platform.properties, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/11762
=> Update error message when search not available

src-web/components/Topology/utils/diagram-helpers.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
Fix open YAML link missing if the ansible job was not found in search
https://github.com/open-cluster-management/backlog/issues/10595
=> ansible link missing when no map resource

src-web/components/Topology/utils/diagram-helpers.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
https://github.com/open-cluster-management/backlog/issues/11750
=> Use an alternative key for the topology resource map

nls/platform.properties, src-web/actions/topology.js, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/11293
=> update error msg for unavailable search

src-web/components/Topology/utils/diagram-helpers-utils.js, src-web/components/Topology/utils/diagram-helpers.js, tests/cypress/views/application.js, tests/cypress/views/common.js, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
https://github.com/open-cluster-management/backlog/issues/11750
Argo route deployment has routes with hash names
=> support routes with hash

build/run-e2e-tests-clusterpool.sh, run-cypress.sh
=> Optimize for new "ck creds" behaviour

src-web/components/Topology/utils/diagram-helpers-utils.js, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
=> fix error on sync controller when parent not found

src-web/components/common/ResourceTable.js, src-web/definitions/hcm-applications.js, tests/cypress/views/application.js, tests/cypress/views/common.js, tests/jest/actions/common.test.js, tests/jest/components/ApplicationsListPage.test.js, tests/jest/components/TestingData.js, tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap, tests/jest/definitions/__snapshots__/index.test.js.snap
open-cluster-management/backlog#9034
=> Fix issue when Argo applications have same name/namespace on different clusters

tests/cypress/config/config.func.yaml, tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js, tests/cypress/tests/02-validate/03-validate-ui-single-app.spec.js, tests/cypress/views/application.js
https://github.com/open-cluster-management/backlog/issues/11645
- Add validations for deployedNamespace on the application table
=> add validation for deployedNamespace

src-web/definitions/hcm-applications.js
open-cluster-management/backlog#11885
=> Disable delete for for Argo apps

src-web/components/common/AutoRefreshSelect.js, src-web/reducers/common.js, tests/jest/components/TestingData.js, tests/jest/components/common/AutoRefreshSelect_appsTable.test.js, tests/jest/components/common/AutoRefreshSelect_singleApp.test.js, tests/jest/components/common/__snapshots__/AutoRefreshSelect_appsTable.test.js.snap, tests/jest/components/common/__snapshots__/AutoRefreshSelect_singleApp.test.js.snap, tests/jest/reducers/common.test.js
https://github.com/open-cluster-management/backlog/issues/11929
=> skip refresh if called less then 5s after the last fetch completed

src-web/components/common/AutoRefreshSelect.js
open-cluster-management/backlog#11929
=> fix code smell

tests/cypress/config/index.js, tests/cypress/tests/rbac_tests/02-view-application-with-rbacuser.js
Signed-off-by: rovyas <rovyas@redhat.com>
=> fix e2e issue

src-web/components/modals/RemoveResourceModal.js
https://github.com/open-cluster-management/backlog/issues/12056
=> Handle null apiversion on remove resource modal load

src-web/components/Topology/utils/diagram-helpers.js, src-web/definitions/hcm-applications.js
fix for:
- https://sonarcloud.io/project/issues?id=open-cluster-management_application-ui&open=AXkOonwERjkXPPWK-Qht&resolved=false&types=BUG
- https://sonarcloud.io/project/issues?id=open-cluster-management_application-ui&open=AXkOonrPRjkXPPWK-QhJ&resolved=false&types=CODE_SMELL
=> fix sonar bug and code smell

tests/cypress/support/index.js, tests/start-cypress-tests.sh
https://github.com/open-cluster-management/acm-qe/issues/284
=> Detect install namespace dynamically

tests/cypress/support/commands.js, tests/cypress/support/index.js, tests/cypress/views/resources.js
https://github.com/open-cluster-management/backlog/issues/12403
https://github.com/open-cluster-management/backlog/issues/12408
=> fix canary

src-web/actions/topology.js, src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js, src-web/components/common/AutoRefreshSelect.js, tests/cypress/tests/02-validate/01-validate-ui-advanced-table.spec.js, tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js
https://github.com/open-cluster-management/backlog/issues/12447
=> argo editor not opening when cluster not in URL

src-web/components/Topology/utils/diagram-helpers.js, src-web/reducers/data-mappers/mapApplicationsSingle.js, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js
=> fix error display

src-web/components/ApplicationCreationPage/controlData/utils.js
https://github.com/open-cluster-management/backlog/issues/12522
=> count channel name usage

scss/common.scss, scss/secondary-header.scss, src-web/components/ApplicationCreationPage/ApplicationCreationPage.js
https://github.com/open-cluster-management/backlog/issues/12280
=> change editor background color to white

tests/cypress/support/commands.js
https://github.com/open-cluster-management/backlog/issues/12552
=> ignore cypress error when requesting token

src-web/components/ApplicationTopologyModule/definitions/hcm-application-diagram.js, src-web/components/Topology/utils/diagram-helpers-utils.js, src-web/components/Topology/utils/diagram-helpers.js, tests/jest/components/Topology/viewer/utils/diagram-helpers-utils.test.js
https://github.com/open-cluster-management/backlog/issues/9317
=> call refresh ui model only when data changed

tests/cypress/support/commands.js
https://github.com/open-cluster-management/backlog/issues/12591
=> clean up auth cookie when switching users

src-web/components/ApplicationCreationPage/controlData/utils.js, tests/cypress/config/config.func.yaml, tests/cypress/templates/secret_yaml/ansible-secret.yaml
open-cluster-management/backlog#12608
=> change ansible label

tests/cypress/support/commands.js, tests/cypress/support/index.js, tests/cypress/views/resources.js
* add failOnNonZeroExit
* hide log
* add failOnNonZeroExit to hide credentials
https://github.com/open-cluster-management/backlog/issues/12582
=> fix canary (#1195)

scss/common.scss, src-web/actions/common.js, src-web/definitions/hcm-applications.js
=> Fix bugs detected by Sonar

Makefile, build/run-e2e-tests-clusterpool.sh, tests/cypress/scripts/slack-reporter.js
=> Remove GitHub token where no longer needed

tests/cypress/config/config.func.yaml
=> enable ansible test

src-web/components/common-apollo/ActionModalApollo.js, src-web/components/common/OverviewCards/index.js, src-web/components/modals/RemoveResourceModal.js, src-web/components/modals/SyncResourceModal.js, tests/jest/components/modal/RemoveResourceModal.test.js, tests/jest/components/modal/RemoveResourceModal_onClose.test.js, tests/jest/components/modal/__snapshots__/RemoveResourceModal.test.js.snap, tests/jest/components/modal/__snapshots__/RemoveResourceModal_onClose.test.js.snap
A code clean-up along with https://github.com/open-cluster-management/backlog/issues/12699
=> Use QueryApplications resource type for modals

package-lock.json, package.json, tests/cypress/views/application.js, tests/cypress/views/common.js
https://github.com/open-cluster-management/backlog/issues/12691
=> Fix app editor alerts

tests/cypress/views/application.js
open-cluster-management/backlog#12699
=> Make sure success alert appears for advanced delete

.dockerignore, Dockerfile.cypress, Makefile
https://github.com/open-cluster-management/backlog/issues/12663
=> refactor dockerfile

Makefile.prow, build/run-prow-e2e.sh
=> add an e2e test

src-web/components/ApplicationCreationPage/controlData/ControlDataPrePostTasks.js
Add the missing multicloud parameter
=> fix credential url

nls/platform.properties, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/12808
=> Refactor the tooltip

tests/cypress/views/resources.js
open-cluster-management/backlog#12924
=> Fix getSavedPathname

tests/cypress/config/config.func.yaml, tests/cypress/support/index.js
Needed to test the new script in https://github.com/open-cluster-management/application-ui/pull/1250
=> Disable argocd e2e tests on PR builds

tests/cypress/config/config.func.yaml, tests/cypress/scripts/argocd-integration.sh, tests/cypress/support/argocdoperator.js, tests/cypress/support/index.js, tests/cypress/templates/argocd_yaml/argocd-operator.yaml, tests/cypress/templates/argocd_yaml/argocd-resource.yaml
https://github.com/open-cluster-management/backlog/issues/11483
=> Use openshift gitops operator for argo apps e2e tests

nls/platform.properties, src-web/components/Topology/utils/diagram-helpers.js, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/12101
- Check and display zombie clusters when we find them
=> Display zombie clusters

Dockerfile.prow
https://github.com/open-cluster-management/backlog/issues/11308
=> remove amd64 from image name

lib/client/apollo-client.js, lib/client/queries.js, src-web/components/ApplicationCreationPage/controlData/ControlDataPlacement.js, tests/jest/components/CreateApplicationPage/CreateApplicationPage.test.js, tests/jest/lib/client/resource-helper.test.js
https://github.com/open-cluster-management/backlog/issues/12797
=> use console-api query to determine managedcluster

Dockerfile, Dockerfile.prow
open-cluster-management/backlog#13008
=> Synchronize Dockerfiles for old upstream and Prow

package-lock.json, tests/package-lock.json
open-cluster-management/backlog#12819
=> Upgrade dependences

src-web/actions/topology.js
Fix https://github.com/open-cluster-management/backlog/issues/12910
=> Fix argocd route

tests/cypress/config/config.func.yaml, tests/cypress/scripts/argocd-integration.sh, tests/cypress/support/index.js, tests/cypress/templates/argocd_yaml/gitopscluster.yaml, tests/cypress/templates/argocd_yaml/managedclusterset.yaml, tests/cypress/templates/argocd_yaml/managedclustersetbinding.yaml, tests/cypress/templates/argocd_yaml/placement.yaml, tests/cypress/views/application.js, tests/cypress/views/common.js
https://github.com/open-cluster-management/backlog/issues/11483
=> Update ArgoCD test scripts to use GitOpsCluster CR

package-lock.json, tests/jest/components/common/__snapshots__/LabelWithPopover.test.js.snap
open-cluster-management/backlog#12819
=> npm audit fix for glob-parent

package-lock.json, package.json, tests/cypress/views/application.js, tests/cypress/views/common.js, tests/package-lock.json, tests/package.json
=> update cypress and chromedriver version

package-lock.json
https://github.com/open-cluster-management/backlog/issues/12932
=> More package updates

Dockerfile.cypress, tests/cypress/views/application.js, tests/cypress/views/common.js, tests/start-cypress-tests.sh
Fixed a few issues in Dockerfile.cypress 
Ran `run-prow-e2e.sh` successfully inside docker
=> fix e2e script and disable cluster validation

run-cypress.sh, tests/cypress/views/application.js, tests/cypress/views/common.js
open-cluster-management/backlog#13196
=> Turn on cluster count checking

tests/cypress/views/application.js, tests/cypress/views/common.js
This reverts commit 39cb03ef19aa92e04a947e58dd953cf7f90c7286.
open-cluster-management/backlog#13196
=> Revert "Turn on cluster count checking (#1279)"

package-lock.json, package.json, src-web/components/common/ResourceTable.js, tests/cypress/views/application.js, tests/cypress/views/common.js
https://github.com/open-cluster-management/backlog/issues/12961
=> update graphics for empty state tables

lib/shared/constants.js, tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap, tests/jest/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/__snapshots__/ApplicationDeploymentHighlightsTerminology.test.js.snap, tests/jest/components/__snapshots__/ApplicationDeploymentHighlights.test.js.snap
https://github.com/open-cluster-management/backlog/issues/13159
=> change the 2.2 link to 2.3

Dockerfile.cypress, README.md, tests/run-prow-e2e.sh, tests/start-cypress-tests.sh
=> fix permission restriction

tests/cypress/config/config.e2e.yaml, tests/cypress/config/config.func.yaml, tests/cypress/config/config.rbac.yaml
https://github.com/open-cluster-management/backlog/issues/13574
=> change test branch name from master to main

Dockerfile.cypress, tests/cypress/plugins/index.js, tests/cypress/scripts/argocd-integration.sh, tests/cypress/support/index.js, tests/cypress/tests/01-create/01-git-connection-tests.js, tests/cypress/tests/02-validate/02-validate-ui-app-table.spec.js, tests/cypress/tests/02-validate/03-validate-ui-single-app.spec.js, tests/cypress/tests/04-delete/01-delete-app.spec.js, tests/cypress/tests/04-delete/02-validate-hub-resource-deletion.spec.js, tests/cypress/tests/04-delete/03-delete-resources.spec.js, tests/download-clis.sh, tests/run-prow-e2e.sh
https://github.com/open-cluster-management/backlog/issues/13503
=> Enable PR tests in Prow

tests/cypress/config/config.e2e.yaml, tests/cypress/config/config.func.yaml
https://github.com/open-cluster-management/backlog/issues/13610
=> 2.1 change branch name from master to main

tests/cypress/templates/secret_yaml/ansible-secret.yaml
=> Update annnotation for Ansible secret so it appears in Credentials

nls/platform.properties, tests/jest/config/platform-properties.json
https://github.com/open-cluster-management/backlog/issues/14009
**Before**
---
**After**
=> Add missing label for chart property

lib/shared/constants.js, tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap, tests/jest/components/ApplicationDeploymentHighlights/ApplicationDeploymentHighlightsTerminology/__snapshots__/ApplicationDeploymentHighlightsTerminology.test.js.snap, tests/jest/components/__snapshots__/ApplicationDeploymentHighlights.test.js.snap
open-cluster-management/backlog#13159
=> Updated docs link; remove unused links

Dockerfile.prow
fixes https://github.com/open-cluster-management/backlog/issues/14429
=> Fix security scan

Dockerfile.prow
https://github.com/open-cluster-management/backlog/issues/14429
=> Fix security scan for main

OWNERS
https://github.com/open-cluster-management/backlog/issues/14277
=> Add owners for console team

src-web/components/common/ResourceList.js, tests/jest/components/AdvancedConfigurationPage/__snapshots__/AdvancedConfigurationPage.test.js.snap, tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
https://github.com/open-cluster-management/backlog/issues/14786
=> update successful delete msg to toast alert

lib/client/resource-helper.js, scss/channel-labels.scss, scss/label-with-popover.scss, scss/time-window-labels.scss, src-web/components/common/ChannelLabels.js, src-web/components/common/LabelWithPopover.js
https://github.com/open-cluster-management/backlog/issues/14595
@heyethankim  redesigned the popovers for GRC, so updating them here first and then will incorporate in GRC policy table.
=> Update style of popovers

tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
Related issue: https://github.com/open-cluster-management/backlog/issues/15228
- No-op commit to trigger new build for CVE
=> Trigger new build to pick up CVE fix in 2.3

src-web/components/ArgoCreationPage/controlData/ControlDataPlacement.js, src-web/components/ArgoCreationPage/templates/template.hbs
https://github.com/open-cluster-management/backlog/issues/15802
=> Fix placement reverse

src-web/components/ArgoCreationPage/ArgoCreationPage.js
Create argo app set will redirect to application table.
https://github.com/open-cluster-management/backlog/issues/15779
=> Redirect to table page

package-lock.json, package.json, src-web/components/ArgoCreationPage/ArgoCreationPage.js, src-web/components/ArgoCreationPage/style.scss, src-web/components/ArgoCreationPage/transformers/transform-resources-to-controls.js, tests/cypress/views/application.js, tests/cypress/views/common.js, tests/cypress/views/resources.js, tests/jest/components/CreateArgoPage/__snapshots__/ArgoApplicationPage.test.js.snap
https://github.com/open-cluster-management/backlog/issues/15582
=> Issue15582

src-web/components/Topology/utils/diagram-helpers.js, src-web/components/Topology/viewer/defaults/details.js, tests/jest/components/Topology/viewer/defaults/details.test.js
https://github.com/open-cluster-management/backlog/issues/15198
=> Create placement node

tests/jest/components/__snapshots__/ApplicationsListPage.test.js.snap
https://github.com/open-cluster-management/backlog/issues/16226
=> Fix unit test failure

package-lock.json, package.json, scss/table.scss, src-web/components/common/ChannelLabels.js, src-web/definitions/hcm-applications.js, tests/package-lock.json, tests/package.json
Related issues:
- https://github.com/open-cluster-management/backlog/issues/16209
- https://github.com/open-cluster-management/backlog/issues/16055
Changes made:
- Change app count to use PF badge component
- Also changed the other balloon colours to grey as the badge didn't have a light blue colour
- Remove padding for create app dropdown
=> Change app count to use PF badge component

tests/cypress/config/users.yaml, tests/cypress/support/index.js, tests/cypress/templates/rbac_yaml/e2e-rbac-clusterrolebinding.yaml
Related issue: https://github.com/open-cluster-management/backlog/issues/15899
- Changed our RBAC usernames in case of conflict with other components
- Clear auth cookies before test starts
=> Attempt to fix invalid token issue in canary

src-web/components/common/ResourceOverview/utils.js
https://github.com/open-cluster-management/backlog/issues/16179
=> Fix invalid pre-set search query for argo apps

src-web/components/Topology/viewer/DiagramViewer.js
Signed-off-by: James Talton <jtalton@redhat.com>
https://github.com/open-cluster-management/backlog/issues/13957
=> Fix topology view messing up after whitespace click

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/16781
=> Attempt to fix jsesc problem

src-web/actions/topology.js, src-web/components/ApplicationCreationPage/components/TimeWindow.js, src-web/components/ApplicationCreationPage/controlData/ControlDataPlacement.js, src-web/components/Topology/utils/diagram-helpers.js, src-web/components/Topology/viewer/ClusterDetailsContainer.js, src-web/definitions/hcm-applications.js
https://github.com/open-cluster-management/backlog/issues/16753
=> Fix code smells

src-web/components/ArgoCreationPage/controlData/ControlDataHelm.js
https://github.com/open-cluster-management/backlog/issues/17470
=> Fix bogus channel

tests/cypress/support/useradd.js
https://github.com/open-cluster-management/backlog/issues/17703
=> Wait for 5 mins to register idp

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/18158
=> Fix clear all filters

package-lock.json, package.json
https://github.com/open-cluster-management/backlog/issues/18101
=> [2.4] Update json-schema

package-lock.json, package.json
open-cluster-management/backlog#18101
=> [main] Update to json-schema 0.40.0

src-web/components/Topology/utils/diagram-helpers.js, tests/cypress/templates/ansible_yaml/ansible-subscription.yaml, tests/cypress/templates/argocd_yaml/argocd-operator.yaml, tests/cypress/templates/argocd_yaml/managedclustersetbinding.yaml, tests/jest/components/Topology/viewer/utils/diagram-helpers.test.js, tests/run-prow-e2e.sh
https://github.com/stolostron/backlog/issues/19023
https://github.com/stolostron/backlog/issues/17130
=> Fix CRD status

Dockerfile.cypress, Makefile, README.md, auth-setup/mcm-application-ui-app.yaml, build/run-e2e-tests-clusterpool.sh, controllers/ui/index.js, options.yaml, package-lock.json, package.json, src-web/components/AdvancedConfigurationLists.js, src-web/components/ApplicationTopologyModule/ApplicationTopologyModule.js, src-web/components/ApplicationsListPage.js, src-web/components/Topology/Topology.js, src-web/components/common/CreateApplicationButton.js, src-web/components/common/OverviewCards/index.js, src-web/components/common/ResourceDetails/index.js, src-web/components/common/ResourceList.js, src-web/components/common/ResourceTable.js, src-web/components/modals/RemoveResourceModal.js, tests/cypress/README.md, tests/cypress/scripts/slack-reporter.js, tests/cypress/views/common.js, webpack.config.js
https://github.com/stolostron/backlog/issues/18716
=> [release-2.2] Switch GH org to stolostron

tests/cypress/templates/ansible_yaml/ansible-operator-group.yaml, tests/cypress/templates/ansible_yaml/ansible-subscription.yaml
May address Ansible related failures in:
stolostron/backlog#19290
stolostron/backlog#19401
stolostron/backlog#19385
=> Use cluster-scoped Ansible

tests/cypress/templates/argocd_yaml/argocd-operator.yaml
Fix the argo install failure - test only
=> Fix-argo-install
